name: BorderRadius
author: minhlong139
category: Interface
tags: [border, corner, radius]
docs: http://minhlong139.plus.vn/BorderRadius/Docs/
demo: http://minhlong139.plus.vn/BorderRadius/demo/
current: 1.2
